import { useState } from "react";
import { Link, Outlet } from "react-router";

import Header from "./components/Header";
import Footer from "./components/Footer";

import {
  PortfolioContext,
    type PortfolioData,
    } from "./PortfolioContext";

    import calcImg from "./assets/calc.jpg";
    import herosImg from "./assets/heros.jpg";
    import carsImg from "./assets/cars.jpg";
    import reactApp from "./assets/reactApp.jpeg";
    import sheridanImg from "./assets/sheridan.jpg";

    import "./App.css";

    export default function App() {
      const [darkMode, setDarkMode] = useState(false);

        function handleDarkModeChange() {
            setDarkMode(!darkMode);
              }

                const portfolioData: PortfolioData = {
                    header: {
                          name: "Simon Jaramillo",
                                role:
                                        "Second Year Sheridan Software Engineering Student and Aspiring AI Engineer",
                                              motto: "Building the tools that change the world",
                                                  },

                                                      about: {
                                                            paragraph:
                                                                    "I'm a student at Sheridan College. My passion is learning how to develop tools that can make a change in society. This portfolio includes projects that helped me practise components, data structures, list rendering, conditional rendering, and semantic HTML.",
                                                                        },

                                                                            contact: {
                                                                                  email: "jaramisi@sheridancollege.ca",
                                                                                      },

                                                                                          projects: [
                                                                                                {
                                                                                                        id: 1,
                                                                                                                title: "Superhero Name Generator",
                                                                                                                        description:
                                                                                                                                  "A fun JavaScript project that generates random superhero names using arrays, variables, and functions. The application combines different words together to create unique superhero identities.",
                                                                                                                                          image: herosImg,
                                                                                                                                                  important: true,
                                                                                                                                                        },

                                                                                                                                                              {
                                                                                                                                                                      id: 2,
                                                                                                                                                                              title: "Tax Calculator App",
                                                                                                                                                                                      description:
                                                                                                                                                                                                "A JavaScript tax calculator that allows users to enter income values and calculate estimated taxes dynamically. The project uses variables, functions, user input, and mathematical calculations.",
                                                                                                                                                                                                        image: calcImg,
                                                                                                                                                                                                                important: true,
                                                                                                                                                                                                                      },

                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                    id: 3,
                                                                                                                                                                                                                                            title: "Highway Escape",
                                                                                                                                                                                                                                                    description:
                                                                                                                                                                                                                                                              "A driving game inspired by classic arcade games where the player avoids traffic and obstacles while surviving as long as possible on the highway. The project uses JavaScript logic, movement controls, and collision detection.",
                                                                                                                                                                                                                                                                      image: carsImg,
                                                                                                                                                                                                                                                                              important: false,
                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                  id: 4,
                                                                                                                                                                                                                                                                                                          title: "React Developer Portfolio",
                                                                                                                                                                                                                                                                                                                  description:
                                                                                                                                                                                                                                                                                                                            "A personal portfolio created with React components, props, list rendering, conditional rendering, and CSS.",
                                                                                                                                                                                                                                                                                                                                    image: reactApp,
                                                                                                                                                                                                                                                                                                                                            important: false,
                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                id: 5,
                                                                                                                                                                                                                                                                                                                                                                        title: "Sheridan Student Dashboard",
                                                                                                                                                                                                                                                                                                                                                                                description:
                                                                                                                                                                                                                                                                                                                                                                                          "A web page showing student information using semantic HTML, CSS styling, and embedded variables.",
                                                                                                                                                                                                                                                                                                                                                                                                  image: sheridanImg,
                                                                                                                                                                                                                                                                                                                                                                                                          important: false,
                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                    ],

                                                                                                                                                                                                                                                                                                                                                                                                                        footer: {
                                                                                                                                                                                                                                                                                                                                                                                                                              socialLinks: [
                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          name: "LinkedIn",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url: "https://www.linkedin.com/in/sjaramillo12",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: "Instagram",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  url: "https://www.instagram.com/sjaramilllo?igsh=MWJmbWt3bTA3bDN4bg%3D%3D&utm_source=qr",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id: 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name: "YouTube",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                url: "https://www.youtube.com/@coldbeatzzz",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    technologies: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { id: 1, name: "React" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { id: 2, name: "TypeScript" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { id: 3, name: "HTML" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { id: 4, name: "CSS" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { id: 5, name: "Vite" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { id: 6, name: "Tailwind" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { id: 7, name: "shadcn" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Provider makes the complete portfolioData object available to the components inside.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <PortfolioContext value={portfolioData}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className={darkMode ? "app dark" : "app"}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Header />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/*Move between routes without reloading the page*/}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <nav className="flex flex-wrap items-center justify-center gap-3 p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white hover:bg-blue-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Projects
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to="/about"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white hover:bg-blue-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          About
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          to="/contact"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white hover:bg-blue-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Contact
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <main className="main-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="dark-mode-control flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        checked={darkMode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleDarkModeChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Dark Mode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Outlet />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/*header, outlet, footer are outside of outlet, so they remain visible on every page*/}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </PortfolioContext>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }